// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop_tb.h for the primary calling header

#include "Vtop_tb__pch.h"
#include "Vtop_tb_top_tb.h"

VL_ATTR_COLD void Vtop_tb_top_tb___eval_static__TOP__top_tb(Vtop_tb_top_tb* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+      Vtop_tb_top_tb___eval_static__TOP__top_tb\n"); );
    // Body
    vlSelf->__PVT__monitor__DOT__inst_count = 0ULL;
    vlSelf->__PVT__monitor__DOT__cycle_count = 0ULL;
    vlSelf->__PVT__monitor__DOT__start_time = 0ULL;
    vlSelf->__PVT__monitor__DOT__total_time = 0ULL;
    vlSelf->__PVT__monitor__DOT__done_print_ipc = 0U;
    vlSelf->__PVT__monitor__DOT__ipc = 0.0;
}

VL_ATTR_COLD void Vtop_tb_top_tb___eval_final__TOP__top_tb(Vtop_tb_top_tb* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+      Vtop_tb_top_tb___eval_final__TOP__top_tb\n"); );
    // Body
    VL_FCLOSE_I(vlSelf->__PVT__fd); if (VL_UNLIKELY(
                                                    (1U 
                                                     & (~ (IData)(vlSelf->__PVT__monitor__DOT__done_print_ipc))))) {
        vlSelf->__PVT__monitor__DOT__ipc = (VL_ISTOR_D_Q(64, vlSelf->__PVT__monitor__DOT__inst_count) 
                                            / VL_ISTOR_D_Q(64, vlSelf->__PVT__monitor__DOT__cycle_count));
        vlSelf->__PVT__monitor__DOT__total_time = ((QData)(VL_TIME_UNITED_Q(1)) 
                                                   - vlSelf->__PVT__monitor__DOT__start_time);
        VL_WRITEF("Monitor: Total IPC: %f\nMonitor: Total Time: %t\n",
                  64,vlSelf->__PVT__monitor__DOT__ipc,
                  64,vlSelf->__PVT__monitor__DOT__total_time,
                  -12);
    }
    VL_FCLOSE_I(vlSelf->__PVT__monitor__DOT__fd); }

VL_ATTR_COLD void Vtop_tb_top_tb___ctor_var_reset(Vtop_tb_top_tb* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+      Vtop_tb_top_tb___ctor_var_reset\n"); );
    // Body
    vlSelf->clk = VL_RAND_RESET_I(1);
    vlSelf->rst = VL_RAND_RESET_I(1);
    vlSelf->dut_rst = VL_RAND_RESET_I(1);
    vlSelf->imem_rdata = VL_RAND_RESET_I(32);
    vlSelf->imem_resp = VL_RAND_RESET_I(1);
    vlSelf->imem_addr = VL_RAND_RESET_I(32);
    vlSelf->imem_read = VL_RAND_RESET_I(1);
    vlSelf->dmem_rdata = VL_RAND_RESET_I(32);
    vlSelf->dmem_resp = VL_RAND_RESET_I(1);
    vlSelf->dmem_addr = VL_RAND_RESET_I(32);
    vlSelf->dmem_read = VL_RAND_RESET_I(1);
    vlSelf->dmem_write = VL_RAND_RESET_I(1);
    vlSelf->dmem_wmask = VL_RAND_RESET_I(4);
    vlSelf->dmem_wdata = VL_RAND_RESET_I(32);
    vlSelf->golden_imem_rdata = VL_RAND_RESET_I(32);
    vlSelf->golden_imem_resp = VL_RAND_RESET_I(1);
    vlSelf->golden_imem_addr = VL_RAND_RESET_I(32);
    vlSelf->golden_imem_read = VL_RAND_RESET_I(1);
    vlSelf->golden_dmem_rdata = VL_RAND_RESET_I(32);
    vlSelf->golden_dmem_resp = VL_RAND_RESET_I(1);
    vlSelf->golden_dmem_addr = VL_RAND_RESET_I(32);
    vlSelf->golden_dmem_read = VL_RAND_RESET_I(1);
    vlSelf->golden_dmem_write = VL_RAND_RESET_I(1);
    vlSelf->golden_dmem_wmask = VL_RAND_RESET_I(4);
    vlSelf->golden_dmem_wdata = VL_RAND_RESET_I(32);
    vlSelf->halt = VL_RAND_RESET_I(1);
    vlSelf->error = VL_RAND_RESET_I(1);
    vlSelf->any_commit = VL_RAND_RESET_I(1);
    vlSelf->mispredict_o = VL_RAND_RESET_I(1);
    vlSelf->eoc_enable = VL_RAND_RESET_I(1);
    vlSelf->dut_order = VL_RAND_RESET_Q(64);
    vlSelf->dut_pc = VL_RAND_RESET_I(32);
    vlSelf->dut_inst = VL_RAND_RESET_I(32);
    vlSelf->dut_rd_addr = VL_RAND_RESET_I(5);
    vlSelf->dut_rd_wdata = VL_RAND_RESET_I(32);
    vlSelf->dut_mem_addr = VL_RAND_RESET_I(32);
    vlSelf->dut_mem_rmask = VL_RAND_RESET_I(4);
    vlSelf->dut_mem_wmask = VL_RAND_RESET_I(4);
    vlSelf->dut_mem_rdata = VL_RAND_RESET_I(32);
    vlSelf->dut_mem_wdata = VL_RAND_RESET_I(32);
    vlSelf->golden_commit = VL_RAND_RESET_I(1);
    vlSelf->golden_order = VL_RAND_RESET_Q(64);
    vlSelf->golden_pc = VL_RAND_RESET_I(32);
    vlSelf->golden_inst = VL_RAND_RESET_I(32);
    vlSelf->golden_rd_addr = VL_RAND_RESET_I(5);
    vlSelf->golden_rd_wdata = VL_RAND_RESET_I(32);
    vlSelf->golden_mem_addr = VL_RAND_RESET_I(32);
    vlSelf->golden_mem_rmask = VL_RAND_RESET_I(4);
    vlSelf->golden_mem_wmask = VL_RAND_RESET_I(4);
    vlSelf->golden_mem_rdata = VL_RAND_RESET_I(32);
    vlSelf->golden_mem_wdata = VL_RAND_RESET_I(32);
    vlSelf->__Vcellinp__dut__rst = VL_RAND_RESET_I(1);
    vlSelf->__PVT__lcom = 0;
    vlSelf->__PVT__cycles = 0;
    vlSelf->__PVT__total_cycles = 0;
    vlSelf->__PVT__fd = 0;
    vlSelf->__PVT__halt_seen = VL_RAND_RESET_I(1);
    vlSelf->__PVT__unnamedblk2__DOT__i = 0;
    vlSelf->__PVT__eoc_checker__DOT__expected_free = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__eoc_checker__DOT__err_cnt = 0;
    vlSelf->__PVT__eoc_checker__DOT__free_cnt = 0;
    vlSelf->__PVT__eoc_checker__DOT__unnamedblk3__DOT__x0_ok = VL_RAND_RESET_I(1);
    vlSelf->__PVT__eoc_checker__DOT__unnamedblk4__DOT__alloc_ok = VL_RAND_RESET_I(1);
    vlSelf->__PVT__eoc_checker__DOT__unnamedblk4__DOT__unnamedblk5__DOT__i = 0;
    vlSelf->__PVT__eoc_checker__DOT__unnamedblk6__DOT__overlap = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__eoc_checker__DOT__unnamedblk7__DOT__drained = VL_RAND_RESET_I(1);
    vlSelf->__PVT__eoc_checker__DOT__unnamedblk7__DOT__unnamedblk8__DOT__i = 0;
    vlSelf->__PVT__eoc_checker__DOT__unnamedblk7__DOT__unnamedblk9__DOT__i = 0;
    vlSelf->__PVT__eoc_checker__DOT__unnamedblk7__DOT__unnamedblk10__DOT__i = 0;
    vlSelf->__PVT__eoc_checker__DOT__unnamedblk11__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__rvfi_valid = VL_RAND_RESET_I(8);
    VL_RAND_RESET_W(512, vlSelf->__PVT__monitor__DOT__rvfi_order);
    VL_RAND_RESET_W(256, vlSelf->__PVT__monitor__DOT__rvfi_insn);
    vlSelf->__PVT__monitor__DOT__rvfi_halt = VL_RAND_RESET_I(8);
    vlSelf->__PVT__monitor__DOT__rvfi_rs1_addr = VL_RAND_RESET_Q(40);
    vlSelf->__PVT__monitor__DOT__rvfi_rs2_addr = VL_RAND_RESET_Q(40);
    VL_RAND_RESET_W(256, vlSelf->__PVT__monitor__DOT__rvfi_rs1_rdata);
    VL_RAND_RESET_W(256, vlSelf->__PVT__monitor__DOT__rvfi_rs2_rdata);
    vlSelf->__PVT__monitor__DOT__rvfi_rd_addr = VL_RAND_RESET_Q(40);
    VL_RAND_RESET_W(256, vlSelf->__PVT__monitor__DOT__rvfi_rd_wdata);
    VL_RAND_RESET_W(256, vlSelf->__PVT__monitor__DOT__rvfi_pc_rdata);
    VL_RAND_RESET_W(256, vlSelf->__PVT__monitor__DOT__rvfi_pc_wdata);
    VL_RAND_RESET_W(256, vlSelf->__PVT__monitor__DOT__rvfi_mem_addr);
    vlSelf->__PVT__monitor__DOT__rvfi_mem_rmask = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__rvfi_mem_wmask = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(256, vlSelf->__PVT__monitor__DOT__rvfi_mem_rdata);
    VL_RAND_RESET_W(256, vlSelf->__PVT__monitor__DOT__rvfi_mem_wdata);
    vlSelf->__PVT__monitor__DOT__errcode = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__inst_count = 0;
    vlSelf->__PVT__monitor__DOT__cycle_count = 0;
    vlSelf->__PVT__monitor__DOT__start_time = 0;
    vlSelf->__PVT__monitor__DOT__total_time = 0;
    vlSelf->__PVT__monitor__DOT__done_print_ipc = 0;
    vlSelf->__PVT__monitor__DOT__ipc = 0;
    vlSelf->__PVT__monitor__DOT__fd = 0;
    vlSelf->__PVT__monitor__DOT__unnamedblk1__DOT__channel = 0;
    vlSelf->__PVT__monitor__DOT__genblk2__BRA__0__KET____DOT__unnamedblk2__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__genblk2__BRA__0__KET____DOT__unnamedblk3__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__genblk2__BRA__1__KET____DOT__unnamedblk2__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__genblk2__BRA__1__KET____DOT__unnamedblk3__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__genblk2__BRA__2__KET____DOT__unnamedblk2__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__genblk2__BRA__2__KET____DOT__unnamedblk3__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__genblk2__BRA__3__KET____DOT__unnamedblk2__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__genblk2__BRA__3__KET____DOT__unnamedblk3__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__genblk2__BRA__4__KET____DOT__unnamedblk2__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__genblk2__BRA__4__KET____DOT__unnamedblk3__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__genblk2__BRA__5__KET____DOT__unnamedblk2__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__genblk2__BRA__5__KET____DOT__unnamedblk3__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__genblk2__BRA__6__KET____DOT__unnamedblk2__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__genblk2__BRA__6__KET____DOT__unnamedblk3__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__genblk2__BRA__7__KET____DOT__unnamedblk2__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__genblk2__BRA__7__KET____DOT__unnamedblk3__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__unnamedblk4__DOT__channel = 0;
    vlSelf->__PVT__monitor__DOT__unnamedblk5__DOT__channel = 0;
    vlSelf->__PVT__monitor__DOT__unnamedblk6__DOT__channel = 0;
    vlSelf->__PVT__monitor__DOT__unnamedblk7__DOT__channel = 0;
    vlSelf->__PVT__monitor__DOT__unnamedblk7__DOT__unnamedblk8__DOT__first_1 = 0;
    vlSelf->__PVT__monitor__DOT__unnamedblk7__DOT__unnamedblk8__DOT__unnamedblk9__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__unnamedblk7__DOT__unnamedblk10__DOT__amount_o_1 = 0;
    vlSelf->__PVT__monitor__DOT__unnamedblk7__DOT__unnamedblk10__DOT__first_1 = 0;
    vlSelf->__PVT__monitor__DOT__unnamedblk7__DOT__unnamedblk10__DOT__unnamedblk11__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__unnamedblk7__DOT__unnamedblk10__DOT__unnamedblk12__DOT__i = 0;
    vlSelf->__PVT__monitor__DOT__unnamedblk7__DOT__unnamedblk10__DOT__unnamedblk13__DOT__wdata_byte = VL_RAND_RESET_I(8);
    vlSelf->__PVT__monitor__DOT__unnamedblk7__DOT__unnamedblk10__DOT__unnamedblk14__DOT__wdata_half = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ch0_errcode = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ch1_errcode = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ch2_errcode = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ch3_errcode = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ch4_errcode = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ch5_errcode = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ch6_errcode = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ch7_errcode = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o0_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o0_order = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(177, vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o0_data);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o1_order = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(177, vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o1_data);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o2_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o2_order = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(177, vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o2_data);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o3_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o3_order = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(177, vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o3_data);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o4_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o4_order = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(177, vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o4_data);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o5_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o5_order = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(177, vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o5_data);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o6_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o6_order = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(177, vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o6_data);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o7_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o7_order = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(177, vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_o7_data);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob_errcode = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow_pc_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow_pc_trap = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow_pc = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow0_pc_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow0_pc_trap = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow0_pc_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ro0_errcode_p = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow1_pc_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow1_pc_trap = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow1_pc_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ro1_errcode_p = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow2_pc_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow2_pc_trap = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow2_pc_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ro2_errcode_p = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow3_pc_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow3_pc_trap = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow3_pc_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ro3_errcode_p = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow4_pc_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow4_pc_trap = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow4_pc_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ro4_errcode_p = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow5_pc_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow5_pc_trap = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow5_pc_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ro5_errcode_p = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow6_pc_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow6_pc_trap = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow6_pc_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ro6_errcode_p = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow7_pc_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow7_pc_trap = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow7_pc_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ro7_errcode_p = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow_xregs_valid = VL_RAND_RESET_I(32);
    for (int __Vi0 = 0; __Vi0 < 32; ++__Vi0) {
        vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow_xregs[__Vi0] = VL_RAND_RESET_I(32);
    }
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow0_rs1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow0_rs2_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow0_rs1_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow0_rs2_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ro0_errcode_r = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow1_rs1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow1_rs2_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow1_rs1_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow1_rs2_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ro1_errcode_r = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow2_rs1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow2_rs2_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow2_rs1_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow2_rs2_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ro2_errcode_r = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow3_rs1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow3_rs2_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow3_rs1_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow3_rs2_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ro3_errcode_r = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow4_rs1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow4_rs2_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow4_rs1_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow4_rs2_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ro4_errcode_r = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow5_rs1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow5_rs2_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow5_rs1_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow5_rs2_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ro5_errcode_r = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow6_rs1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow6_rs2_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow6_rs1_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow6_rs2_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ro6_errcode_r = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow7_rs1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow7_rs2_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow7_rs1_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__shadow7_rs2_rdata = VL_RAND_RESET_I(32);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__ro7_errcode_r = VL_RAND_RESET_I(16);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h93807142__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_hbe3d468f__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_hffa8ed01__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h6f3e661b__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_hd6ddbe86__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_hc4755b34__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_hfd7abf7f__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h5d544099__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_hd0253a29__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h9705a690__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h04c8a2ce__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h33811742__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_haa96bd01__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h6858561b__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_ha4713db3__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h84139451__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h27236079__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_hf52c9d23__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h239dd55b__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_hff982c99__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h4adc75cb__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h08771295__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h84688035__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h23f458cb__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h9ed75f22__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h854c57e7__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_hd59fb651__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h57b89cc1__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h1d25340f__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h94a69566__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_haca45885__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h6aa7b63f__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h9f209d67__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h821d34ad__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h015e9540__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h8f8de6b2__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h51ddd1ab__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h21754a35__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h6b6e6815__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_he8f201ab__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_hdbc9a842__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h845449ac__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h8fba82b1__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_he0137f2b__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h2c63fb63__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_hac28caa1__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h9a334b54__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_hd9693db6__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h687c3f0f__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_hb0ff9ce3__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h8ec4773d__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h019edc5d__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_hd6c1f5b3__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h2cf8544a__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h6406a584__0 = VL_RAND_RESET_I(1);
    vlSelf->monitor__DOT__monitor__DOT____VdfgExtracted_h458111f9__0 = VL_RAND_RESET_I(1);
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        VL_RAND_RESET_W(241, vlSelf->__PVT__monitor__DOT__monitor__DOT__rob__DOT__buffer[__Vi0]);
    }
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob__DOT__valid = VL_RAND_RESET_I(16);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob__DOT__cursor = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__monitor__DOT__monitor__DOT__rob__DOT__continue_flag = VL_RAND_RESET_I(1);
    vlSelf->__PVT__golden__DOT__state = 0;
    vlSelf->__PVT__golden__DOT__state_next = 0;
    vlSelf->__PVT__golden__DOT__order = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__golden__DOT__commit = VL_RAND_RESET_I(1);
    vlSelf->__PVT__golden__DOT__pc = VL_RAND_RESET_I(32);
    vlSelf->__PVT__golden__DOT__pc_next = VL_RAND_RESET_I(32);
    vlSelf->__PVT__golden__DOT__load_ir = VL_RAND_RESET_I(1);
    vlSelf->__PVT__golden__DOT__i_imm = VL_RAND_RESET_I(32);
    vlSelf->__PVT__golden__DOT__regf_we = VL_RAND_RESET_I(1);
    vlSelf->__PVT__golden__DOT__rs1_v = VL_RAND_RESET_I(32);
    vlSelf->__PVT__golden__DOT__rs2_v = VL_RAND_RESET_I(32);
    vlSelf->__PVT__golden__DOT__rd_v = VL_RAND_RESET_I(32);
    vlSelf->__PVT__golden__DOT__a = VL_RAND_RESET_I(32);
    vlSelf->__PVT__golden__DOT__b = VL_RAND_RESET_I(32);
    vlSelf->__PVT__golden__DOT__aluop = VL_RAND_RESET_I(3);
    vlSelf->__PVT__golden__DOT__cmpop = VL_RAND_RESET_I(3);
    vlSelf->__PVT__golden__DOT__aluout = VL_RAND_RESET_I(32);
    vlSelf->__PVT__golden__DOT__br_en = VL_RAND_RESET_I(1);
    vlSelf->__PVT__golden__DOT__mul_result_ss = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__golden__DOT__dmem_rmask = VL_RAND_RESET_I(4);
    vlSelf->__PVT__golden__DOT__monitor_regf_we = VL_RAND_RESET_I(1);
    vlSelf->__PVT__golden__DOT__ir__DOT__data = VL_RAND_RESET_I(32);
    for (int __Vi0 = 0; __Vi0 < 32; ++__Vi0) {
        vlSelf->__PVT__golden__DOT__regfile__DOT__data[__Vi0] = VL_RAND_RESET_I(32);
    }
    vlSelf->__PVT__golden__DOT__regfile__DOT__unnamedblk1__DOT__i = 0;
    vlSelf->__Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v0 = 0;
    vlSelf->__Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v1 = 0;
    vlSelf->__Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v2 = 0;
    vlSelf->__Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v3 = 0;
    vlSelf->__Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v4 = 0;
    vlSelf->__Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v5 = 0;
    vlSelf->__Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v6 = 0;
    vlSelf->__Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v7 = 0;
    vlSelf->__Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v8 = 0;
    vlSelf->__Vdly__monitor__DOT__monitor__DOT__rob__DOT__valid = VL_RAND_RESET_I(16);
    vlSelf->__Vdlyvdim0__monitor__DOT__monitor__DOT__rob__DOT__buffer__v0 = 0;
    VL_RAND_RESET_W(241, vlSelf->__Vdlyvval__monitor__DOT__monitor__DOT__rob__DOT__buffer__v0);
    vlSelf->__Vdlyvset__monitor__DOT__monitor__DOT__rob__DOT__buffer__v0 = 0;
    vlSelf->__Vdlyvdim0__monitor__DOT__monitor__DOT__rob__DOT__buffer__v1 = 0;
    VL_RAND_RESET_W(241, vlSelf->__Vdlyvval__monitor__DOT__monitor__DOT__rob__DOT__buffer__v1);
    vlSelf->__Vdlyvset__monitor__DOT__monitor__DOT__rob__DOT__buffer__v1 = 0;
    vlSelf->__Vdlyvdim0__monitor__DOT__monitor__DOT__rob__DOT__buffer__v2 = 0;
    VL_RAND_RESET_W(241, vlSelf->__Vdlyvval__monitor__DOT__monitor__DOT__rob__DOT__buffer__v2);
    vlSelf->__Vdlyvset__monitor__DOT__monitor__DOT__rob__DOT__buffer__v2 = 0;
    vlSelf->__Vdlyvdim0__monitor__DOT__monitor__DOT__rob__DOT__buffer__v3 = 0;
    VL_RAND_RESET_W(241, vlSelf->__Vdlyvval__monitor__DOT__monitor__DOT__rob__DOT__buffer__v3);
    vlSelf->__Vdlyvset__monitor__DOT__monitor__DOT__rob__DOT__buffer__v3 = 0;
    vlSelf->__Vdlyvdim0__monitor__DOT__monitor__DOT__rob__DOT__buffer__v4 = 0;
    VL_RAND_RESET_W(241, vlSelf->__Vdlyvval__monitor__DOT__monitor__DOT__rob__DOT__buffer__v4);
    vlSelf->__Vdlyvset__monitor__DOT__monitor__DOT__rob__DOT__buffer__v4 = 0;
    vlSelf->__Vdlyvdim0__monitor__DOT__monitor__DOT__rob__DOT__buffer__v5 = 0;
    VL_RAND_RESET_W(241, vlSelf->__Vdlyvval__monitor__DOT__monitor__DOT__rob__DOT__buffer__v5);
    vlSelf->__Vdlyvset__monitor__DOT__monitor__DOT__rob__DOT__buffer__v5 = 0;
    vlSelf->__Vdlyvdim0__monitor__DOT__monitor__DOT__rob__DOT__buffer__v6 = 0;
    VL_RAND_RESET_W(241, vlSelf->__Vdlyvval__monitor__DOT__monitor__DOT__rob__DOT__buffer__v6);
    vlSelf->__Vdlyvset__monitor__DOT__monitor__DOT__rob__DOT__buffer__v6 = 0;
    vlSelf->__Vdlyvdim0__monitor__DOT__monitor__DOT__rob__DOT__buffer__v7 = 0;
    VL_RAND_RESET_W(241, vlSelf->__Vdlyvval__monitor__DOT__monitor__DOT__rob__DOT__buffer__v7);
    vlSelf->__Vdlyvset__monitor__DOT__monitor__DOT__rob__DOT__buffer__v7 = 0;
}
