// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop_tb.h for the primary calling header

#ifndef VERILATED_VTOP_TB_TOP_TB_H_
#define VERILATED_VTOP_TB_TOP_TB_H_  // guard

#include "verilated.h"
class Vtop_tb_cpu;
class Vtop_tb_mon_itf;
class Vtop_tb_riscv_formal_monitor_rv32imc_isa_spec;


class Vtop_tb__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop_tb_top_tb final : public VerilatedModule {
  public:
    // CELLS
    Vtop_tb_mon_itf* __PVT__mon_itf;
    Vtop_tb_cpu* dut;
    Vtop_tb_riscv_formal_monitor_rv32imc_isa_spec* __PVT__monitor__DOT__monitor__DOT__ch0_isa_spec;
    Vtop_tb_riscv_formal_monitor_rv32imc_isa_spec* __PVT__monitor__DOT__monitor__DOT__ch1_isa_spec;
    Vtop_tb_riscv_formal_monitor_rv32imc_isa_spec* __PVT__monitor__DOT__monitor__DOT__ch2_isa_spec;
    Vtop_tb_riscv_formal_monitor_rv32imc_isa_spec* __PVT__monitor__DOT__monitor__DOT__ch3_isa_spec;
    Vtop_tb_riscv_formal_monitor_rv32imc_isa_spec* __PVT__monitor__DOT__monitor__DOT__ch4_isa_spec;
    Vtop_tb_riscv_formal_monitor_rv32imc_isa_spec* __PVT__monitor__DOT__monitor__DOT__ch5_isa_spec;
    Vtop_tb_riscv_formal_monitor_rv32imc_isa_spec* __PVT__monitor__DOT__monitor__DOT__ch6_isa_spec;
    Vtop_tb_riscv_formal_monitor_rv32imc_isa_spec* __PVT__monitor__DOT__monitor__DOT__ch7_isa_spec;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst,0,0);
        VL_IN8(dut_rst,0,0);
        VL_IN8(imem_resp,0,0);
        VL_OUT8(imem_read,0,0);
        VL_IN8(dmem_resp,0,0);
        VL_OUT8(dmem_read,0,0);
        VL_OUT8(dmem_write,0,0);
        VL_OUT8(dmem_wmask,3,0);
        VL_IN8(golden_imem_resp,0,0);
        VL_OUT8(golden_imem_read,0,0);
        VL_IN8(golden_dmem_resp,0,0);
        VL_OUT8(golden_dmem_read,0,0);
        VL_OUT8(golden_dmem_write,0,0);
        VL_OUT8(golden_dmem_wmask,3,0);
        VL_OUT8(halt,0,0);
        VL_OUT8(error,0,0);
        VL_OUT8(any_commit,0,0);
        VL_OUT8(mispredict_o,0,0);
        VL_IN8(eoc_enable,0,0);
        VL_OUT8(dut_rd_addr,4,0);
        VL_OUT8(dut_mem_rmask,3,0);
        VL_OUT8(dut_mem_wmask,3,0);
        VL_OUT8(golden_commit,0,0);
        VL_OUT8(golden_rd_addr,4,0);
        VL_OUT8(golden_mem_rmask,3,0);
        VL_OUT8(golden_mem_wmask,3,0);
        CData/*0:0*/ __Vcellinp__dut__rst;
        CData/*0:0*/ __PVT__halt_seen;
        CData/*0:0*/ __PVT__eoc_checker__DOT__unnamedblk3__DOT__x0_ok;
        CData/*0:0*/ __PVT__eoc_checker__DOT__unnamedblk4__DOT__alloc_ok;
        CData/*0:0*/ __PVT__eoc_checker__DOT__unnamedblk7__DOT__drained;
        CData/*7:0*/ __PVT__monitor__DOT__rvfi_valid;
        CData/*7:0*/ __PVT__monitor__DOT__rvfi_halt;
        CData/*0:0*/ __PVT__monitor__DOT__done_print_ipc;
        CData/*7:0*/ __PVT__monitor__DOT__unnamedblk7__DOT__unnamedblk10__DOT__unnamedblk13__DOT__wdata_byte;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o0_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o1_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o2_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o3_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o4_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o5_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o6_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o7_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow_pc_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow_pc_trap;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow0_pc_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow0_pc_trap;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow1_pc_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow1_pc_trap;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow2_pc_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow2_pc_trap;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow3_pc_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow3_pc_trap;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow4_pc_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow4_pc_trap;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow5_pc_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow5_pc_trap;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow6_pc_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow6_pc_trap;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow7_pc_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow7_pc_trap;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow0_rs1_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow0_rs2_valid;
    };
    struct {
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow1_rs1_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow1_rs2_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow2_rs1_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow2_rs2_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow3_rs1_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow3_rs2_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow4_rs1_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow4_rs2_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow5_rs1_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow5_rs2_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow6_rs1_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow6_rs2_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow7_rs1_valid;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__shadow7_rs2_valid;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h93807142__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_hbe3d468f__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_hffa8ed01__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h6f3e661b__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_hd6ddbe86__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_hc4755b34__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_hfd7abf7f__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h5d544099__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_hd0253a29__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h9705a690__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h04c8a2ce__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h33811742__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_haa96bd01__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h6858561b__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_ha4713db3__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h84139451__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h27236079__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_hf52c9d23__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h239dd55b__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_hff982c99__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h4adc75cb__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h08771295__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h84688035__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h23f458cb__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h9ed75f22__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h854c57e7__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_hd59fb651__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h57b89cc1__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h1d25340f__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h94a69566__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_haca45885__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h6aa7b63f__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h9f209d67__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h821d34ad__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h015e9540__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h8f8de6b2__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h51ddd1ab__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h21754a35__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h6b6e6815__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_he8f201ab__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_hdbc9a842__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h845449ac__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h8fba82b1__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_he0137f2b__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h2c63fb63__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_hac28caa1__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h9a334b54__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_hd9693db6__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h687c3f0f__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_hb0ff9ce3__0;
    };
    struct {
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h8ec4773d__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h019edc5d__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_hd6c1f5b3__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h2cf8544a__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h6406a584__0;
        CData/*0:0*/ monitor__DOT__monitor__DOT____VdfgExtracted_h458111f9__0;
        CData/*0:0*/ __PVT__monitor__DOT__monitor__DOT__rob__DOT__continue_flag;
        CData/*0:0*/ __PVT__golden__DOT__commit;
        CData/*0:0*/ __PVT__golden__DOT__load_ir;
        CData/*0:0*/ __PVT__golden__DOT__regf_we;
        CData/*2:0*/ __PVT__golden__DOT__aluop;
        CData/*2:0*/ __PVT__golden__DOT__cmpop;
        CData/*0:0*/ __PVT__golden__DOT__br_en;
        CData/*3:0*/ __PVT__golden__DOT__dmem_rmask;
        CData/*0:0*/ __PVT__golden__DOT__monitor_regf_we;
        CData/*0:0*/ __Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v0;
        CData/*0:0*/ __Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v1;
        CData/*0:0*/ __Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v2;
        CData/*0:0*/ __Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v3;
        CData/*0:0*/ __Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v4;
        CData/*0:0*/ __Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v5;
        CData/*0:0*/ __Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v6;
        CData/*0:0*/ __Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v7;
        CData/*0:0*/ __Vdlyvset__monitor__DOT__monitor__DOT__shadow_xregs__v8;
        CData/*3:0*/ __Vdlyvdim0__monitor__DOT__monitor__DOT__rob__DOT__buffer__v0;
        CData/*0:0*/ __Vdlyvset__monitor__DOT__monitor__DOT__rob__DOT__buffer__v0;
        CData/*3:0*/ __Vdlyvdim0__monitor__DOT__monitor__DOT__rob__DOT__buffer__v1;
        CData/*0:0*/ __Vdlyvset__monitor__DOT__monitor__DOT__rob__DOT__buffer__v1;
        CData/*3:0*/ __Vdlyvdim0__monitor__DOT__monitor__DOT__rob__DOT__buffer__v2;
        CData/*0:0*/ __Vdlyvset__monitor__DOT__monitor__DOT__rob__DOT__buffer__v2;
        CData/*3:0*/ __Vdlyvdim0__monitor__DOT__monitor__DOT__rob__DOT__buffer__v3;
        CData/*0:0*/ __Vdlyvset__monitor__DOT__monitor__DOT__rob__DOT__buffer__v3;
        CData/*3:0*/ __Vdlyvdim0__monitor__DOT__monitor__DOT__rob__DOT__buffer__v4;
        CData/*0:0*/ __Vdlyvset__monitor__DOT__monitor__DOT__rob__DOT__buffer__v4;
        CData/*3:0*/ __Vdlyvdim0__monitor__DOT__monitor__DOT__rob__DOT__buffer__v5;
        CData/*0:0*/ __Vdlyvset__monitor__DOT__monitor__DOT__rob__DOT__buffer__v5;
        CData/*3:0*/ __Vdlyvdim0__monitor__DOT__monitor__DOT__rob__DOT__buffer__v6;
        CData/*0:0*/ __Vdlyvset__monitor__DOT__monitor__DOT__rob__DOT__buffer__v6;
        CData/*3:0*/ __Vdlyvdim0__monitor__DOT__monitor__DOT__rob__DOT__buffer__v7;
        CData/*0:0*/ __Vdlyvset__monitor__DOT__monitor__DOT__rob__DOT__buffer__v7;
        SData/*15:0*/ __PVT__monitor__DOT__errcode;
        SData/*15:0*/ __PVT__monitor__DOT__unnamedblk7__DOT__unnamedblk10__DOT__unnamedblk14__DOT__wdata_half;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ch0_errcode;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ch1_errcode;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ch2_errcode;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ch3_errcode;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ch4_errcode;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ch5_errcode;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ch6_errcode;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ch7_errcode;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__rob_errcode;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ro0_errcode_p;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ro1_errcode_p;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ro2_errcode_p;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ro3_errcode_p;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ro4_errcode_p;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ro5_errcode_p;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ro6_errcode_p;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ro7_errcode_p;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ro0_errcode_r;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ro1_errcode_r;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ro2_errcode_r;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ro3_errcode_r;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ro4_errcode_r;
    };
    struct {
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ro5_errcode_r;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ro6_errcode_r;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__ro7_errcode_r;
        SData/*15:0*/ __PVT__monitor__DOT__monitor__DOT__rob__DOT__valid;
        SData/*15:0*/ __Vdly__monitor__DOT__monitor__DOT__rob__DOT__valid;
        VL_IN(imem_rdata,31,0);
        VL_OUT(imem_addr,31,0);
        VL_IN(dmem_rdata,31,0);
        VL_OUT(dmem_addr,31,0);
        VL_OUT(dmem_wdata,31,0);
        VL_IN(golden_imem_rdata,31,0);
        VL_OUT(golden_imem_addr,31,0);
        VL_IN(golden_dmem_rdata,31,0);
        VL_OUT(golden_dmem_addr,31,0);
        VL_OUT(golden_dmem_wdata,31,0);
        VL_OUT(dut_pc,31,0);
        VL_OUT(dut_inst,31,0);
        VL_OUT(dut_rd_wdata,31,0);
        VL_OUT(dut_mem_addr,31,0);
        VL_OUT(dut_mem_rdata,31,0);
        VL_OUT(dut_mem_wdata,31,0);
        VL_OUT(golden_pc,31,0);
        VL_OUT(golden_inst,31,0);
        VL_OUT(golden_rd_wdata,31,0);
        VL_OUT(golden_mem_addr,31,0);
        VL_OUT(golden_mem_rdata,31,0);
        VL_OUT(golden_mem_wdata,31,0);
        IData/*31:0*/ __PVT__fd;
        IData/*31:0*/ __PVT__unnamedblk2__DOT__i;
        IData/*31:0*/ __PVT__eoc_checker__DOT__err_cnt;
        IData/*31:0*/ __PVT__eoc_checker__DOT__free_cnt;
        IData/*31:0*/ __PVT__eoc_checker__DOT__unnamedblk4__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ __PVT__eoc_checker__DOT__unnamedblk7__DOT__unnamedblk8__DOT__i;
        IData/*31:0*/ __PVT__eoc_checker__DOT__unnamedblk7__DOT__unnamedblk9__DOT__i;
        IData/*31:0*/ __PVT__eoc_checker__DOT__unnamedblk7__DOT__unnamedblk10__DOT__i;
        IData/*31:0*/ __PVT__eoc_checker__DOT__unnamedblk11__DOT__i;
        VlWide<16>/*511:0*/ __PVT__monitor__DOT__rvfi_order;
        VlWide<8>/*255:0*/ __PVT__monitor__DOT__rvfi_insn;
        VlWide<8>/*255:0*/ __PVT__monitor__DOT__rvfi_rs1_rdata;
        VlWide<8>/*255:0*/ __PVT__monitor__DOT__rvfi_rs2_rdata;
        VlWide<8>/*255:0*/ __PVT__monitor__DOT__rvfi_rd_wdata;
        VlWide<8>/*255:0*/ __PVT__monitor__DOT__rvfi_pc_rdata;
        VlWide<8>/*255:0*/ __PVT__monitor__DOT__rvfi_pc_wdata;
        VlWide<8>/*255:0*/ __PVT__monitor__DOT__rvfi_mem_addr;
        IData/*31:0*/ __PVT__monitor__DOT__rvfi_mem_rmask;
        IData/*31:0*/ __PVT__monitor__DOT__rvfi_mem_wmask;
        VlWide<8>/*255:0*/ __PVT__monitor__DOT__rvfi_mem_rdata;
        VlWide<8>/*255:0*/ __PVT__monitor__DOT__rvfi_mem_wdata;
        IData/*31:0*/ __PVT__monitor__DOT__fd;
        IData/*31:0*/ __PVT__monitor__DOT__unnamedblk1__DOT__channel;
        IData/*31:0*/ __PVT__monitor__DOT__genblk2__BRA__0__KET____DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ __PVT__monitor__DOT__genblk2__BRA__0__KET____DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ __PVT__monitor__DOT__genblk2__BRA__1__KET____DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ __PVT__monitor__DOT__genblk2__BRA__1__KET____DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ __PVT__monitor__DOT__genblk2__BRA__2__KET____DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ __PVT__monitor__DOT__genblk2__BRA__2__KET____DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ __PVT__monitor__DOT__genblk2__BRA__3__KET____DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ __PVT__monitor__DOT__genblk2__BRA__3__KET____DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ __PVT__monitor__DOT__genblk2__BRA__4__KET____DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ __PVT__monitor__DOT__genblk2__BRA__4__KET____DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ __PVT__monitor__DOT__genblk2__BRA__5__KET____DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ __PVT__monitor__DOT__genblk2__BRA__5__KET____DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ __PVT__monitor__DOT__genblk2__BRA__6__KET____DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ __PVT__monitor__DOT__genblk2__BRA__6__KET____DOT__unnamedblk3__DOT__i;
    };
    struct {
        IData/*31:0*/ __PVT__monitor__DOT__genblk2__BRA__7__KET____DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ __PVT__monitor__DOT__genblk2__BRA__7__KET____DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ __PVT__monitor__DOT__unnamedblk4__DOT__channel;
        IData/*31:0*/ __PVT__monitor__DOT__unnamedblk5__DOT__channel;
        IData/*31:0*/ __PVT__monitor__DOT__unnamedblk6__DOT__channel;
        IData/*31:0*/ __PVT__monitor__DOT__unnamedblk7__DOT__channel;
        IData/*31:0*/ __PVT__monitor__DOT__unnamedblk7__DOT__unnamedblk8__DOT__first_1;
        IData/*31:0*/ __PVT__monitor__DOT__unnamedblk7__DOT__unnamedblk8__DOT__unnamedblk9__DOT__i;
        IData/*31:0*/ __PVT__monitor__DOT__unnamedblk7__DOT__unnamedblk10__DOT__amount_o_1;
        IData/*31:0*/ __PVT__monitor__DOT__unnamedblk7__DOT__unnamedblk10__DOT__first_1;
        IData/*31:0*/ __PVT__monitor__DOT__unnamedblk7__DOT__unnamedblk10__DOT__unnamedblk11__DOT__i;
        IData/*31:0*/ __PVT__monitor__DOT__unnamedblk7__DOT__unnamedblk10__DOT__unnamedblk12__DOT__i;
        VlWide<6>/*176:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o0_data;
        VlWide<6>/*176:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o1_data;
        VlWide<6>/*176:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o2_data;
        VlWide<6>/*176:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o3_data;
        VlWide<6>/*176:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o4_data;
        VlWide<6>/*176:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o5_data;
        VlWide<6>/*176:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o6_data;
        VlWide<6>/*176:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o7_data;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow_pc;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow0_pc_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow1_pc_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow2_pc_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow3_pc_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow4_pc_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow5_pc_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow6_pc_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow7_pc_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow_xregs_valid;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow0_rs1_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow0_rs2_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow1_rs1_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow1_rs2_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow2_rs1_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow2_rs2_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow3_rs1_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow3_rs2_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow4_rs1_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow4_rs2_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow5_rs1_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow5_rs2_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow6_rs1_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow6_rs2_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow7_rs1_rdata;
        IData/*31:0*/ __PVT__monitor__DOT__monitor__DOT__shadow7_rs2_rdata;
        IData/*31:0*/ __PVT__golden__DOT__state;
        IData/*31:0*/ __PVT__golden__DOT__state_next;
        IData/*31:0*/ __PVT__golden__DOT__pc;
        IData/*31:0*/ __PVT__golden__DOT__pc_next;
        IData/*31:0*/ __PVT__golden__DOT__i_imm;
        IData/*31:0*/ __PVT__golden__DOT__rs1_v;
        IData/*31:0*/ __PVT__golden__DOT__rs2_v;
        IData/*31:0*/ __PVT__golden__DOT__rd_v;
        IData/*31:0*/ __PVT__golden__DOT__a;
        IData/*31:0*/ __PVT__golden__DOT__b;
        IData/*31:0*/ __PVT__golden__DOT__aluout;
        IData/*31:0*/ __PVT__golden__DOT__ir__DOT__data;
        IData/*31:0*/ __PVT__golden__DOT__regfile__DOT__unnamedblk1__DOT__i;
        VlWide<8>/*240:0*/ __Vdlyvval__monitor__DOT__monitor__DOT__rob__DOT__buffer__v0;
        VlWide<8>/*240:0*/ __Vdlyvval__monitor__DOT__monitor__DOT__rob__DOT__buffer__v1;
        VlWide<8>/*240:0*/ __Vdlyvval__monitor__DOT__monitor__DOT__rob__DOT__buffer__v2;
        VlWide<8>/*240:0*/ __Vdlyvval__monitor__DOT__monitor__DOT__rob__DOT__buffer__v3;
        VlWide<8>/*240:0*/ __Vdlyvval__monitor__DOT__monitor__DOT__rob__DOT__buffer__v4;
    };
    struct {
        VlWide<8>/*240:0*/ __Vdlyvval__monitor__DOT__monitor__DOT__rob__DOT__buffer__v5;
        VlWide<8>/*240:0*/ __Vdlyvval__monitor__DOT__monitor__DOT__rob__DOT__buffer__v6;
        VlWide<8>/*240:0*/ __Vdlyvval__monitor__DOT__monitor__DOT__rob__DOT__buffer__v7;
        VL_OUT64(dut_order,63,0);
        VL_OUT64(golden_order,63,0);
        QData/*63:0*/ __PVT__lcom;
        QData/*63:0*/ __PVT__cycles;
        QData/*63:0*/ __PVT__total_cycles;
        QData/*63:0*/ __PVT__eoc_checker__DOT__expected_free;
        QData/*63:0*/ __PVT__eoc_checker__DOT__unnamedblk6__DOT__overlap;
        QData/*39:0*/ __PVT__monitor__DOT__rvfi_rs1_addr;
        QData/*39:0*/ __PVT__monitor__DOT__rvfi_rs2_addr;
        QData/*39:0*/ __PVT__monitor__DOT__rvfi_rd_addr;
        QData/*63:0*/ __PVT__monitor__DOT__inst_count;
        QData/*63:0*/ __PVT__monitor__DOT__cycle_count;
        QData/*63:0*/ __PVT__monitor__DOT__start_time;
        QData/*63:0*/ __PVT__monitor__DOT__total_time;
        QData/*63:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o0_order;
        QData/*63:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o1_order;
        QData/*63:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o2_order;
        QData/*63:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o3_order;
        QData/*63:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o4_order;
        QData/*63:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o5_order;
        QData/*63:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o6_order;
        QData/*63:0*/ __PVT__monitor__DOT__monitor__DOT__rob_o7_order;
        QData/*63:0*/ __PVT__monitor__DOT__monitor__DOT__rob__DOT__cursor;
        QData/*63:0*/ __PVT__golden__DOT__order;
        QData/*63:0*/ __PVT__golden__DOT__mul_result_ss;
        VlUnpacked<IData/*31:0*/, 32> __PVT__monitor__DOT__monitor__DOT__shadow_xregs;
        VlUnpacked<VlWide<8>/*240:0*/, 16> __PVT__monitor__DOT__monitor__DOT__rob__DOT__buffer;
        VlUnpacked<IData/*31:0*/, 32> __PVT__golden__DOT__regfile__DOT__data;
    };
    double __PVT__monitor__DOT__ipc;

    // INTERNAL VARIABLES
    Vtop_tb__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtop_tb_top_tb(Vtop_tb__Syms* symsp, const char* v__name);
    ~Vtop_tb_top_tb();
    VL_UNCOPYABLE(Vtop_tb_top_tb);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
